language: go

install:
  - go get github.com/pborman/uuid
  - go get gopkg.in/LeisureLink/httpsig.v1
  - go get gopkg.in/dgrijalva/jwt-go.v3

go:
  - 1.5
  - 1.6
  - 1.7

env:
  global:
    - STREAM_REGION=qa

notifications:
  email:
    - ian@getstream.io

branches:
  only:
  - master
  - dev

after_success:
  - bash <(curl -s https://codecov.io/bash)
